// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nopds.Infrastructure.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Nopds.Infrastructure.Data.Migrations
{
    [DbContext(typeof(NopdsDbContext))]
    [Migration("20260930003935_PreferredFormat")]
    partial class PreferredFormat
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_claims_user_id");

                    b.ToTable("user_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_logins_user_id");

                    b.ToTable("user_logins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_user_tokens");

                    b.ToTable("user_tokens", (string)null);
                });

            modelBuilder.Entity("Nopds.Domain.Entities.Author", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("full_name");

                    b.Property<int>("LangCode")
                        .HasColumnType("integer")
                        .HasColumnName("lang_code");

                    b.Property<string>("SearchName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("search_name");

                    b.HasKey("Id")
                        .HasName("pk_authors");

                    b.HasIndex("LangCode", "SearchName")
                        .HasDatabaseName("ix_authors_lang_code_search_name");

                    b.HasIndex(new[] { "SearchName" }, "ix_authors_search_name")
                        .IsUnique()
                        .HasDatabaseName("ix_authors_search_name");

                    b.HasIndex(new[] { "SearchName" }, "ix_authors_search_name_trgm")
                        .HasDatabaseName("ix_authors_search_name_trgm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex(new[] { "SearchName" }, "ix_authors_search_name_trgm"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex(new[] { "SearchName" }, "ix_authors_search_name_trgm"), new[] { "gin_trgm_ops" });

                    b.ToTable("authors", (string)null);
                });

            modelBuilder.Entity("Nopds.Domain.Entities.Book", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Annotation")
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)")
                        .HasColumnName("annotation");

                    b.Property<long>("CatalogId")
                        .HasColumnType("bigint")
                        .HasColumnName("catalog_id");

                    b.Property<int>("Container")
                        .HasColumnType("integer")
                        .HasColumnName("container");

                    b.Property<long?>("ContentHash")
                        .HasColumnType("bigint")
                        .HasColumnName("content_hash");

                    b.Property<int>("Cover")
                        .HasColumnType("integer")
                        .HasColumnName("cover");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DocDate")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("doc_date");

                    b.Property<long>("DupGroupKey")
                        .HasColumnType("bigint")
                        .HasColumnName("dup_group_key");

                    b.Property<string>("EntryName")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("entry_name");

                    b.Property<DateTimeOffset?>("FileMtime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("file_mtime");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("file_name");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("format");

                    b.Property<string>("KoreaderHash")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("koreader_hash");

                    b.Property<string>("Lang")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("lang");

                    b.Property<int>("LangCode")
                        .HasColumnType("integer")
                        .HasColumnName("lang_code");

                    b.Property<int>("LibraryId")
                        .HasColumnType("integer")
                        .HasColumnName("library_id");

                    b.Property<DateTimeOffset>("RegisteredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registered_at");

                    b.Property<string>("RelPath")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("rel_path");

                    b.Property<string>("SearchTitle")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("search_title");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_books");

                    b.HasIndex("CatalogId")
                        .HasDatabaseName("ix_books_catalog_id");

                    b.HasIndex("ContentHash")
                        .HasDatabaseName("ix_books_content_hash");

                    b.HasIndex("DupGroupKey")
                        .HasDatabaseName("ix_books_dup_group_key");

                    b.HasIndex("KoreaderHash")
                        .HasDatabaseName("ix_books_koreader_hash");

                    b.HasIndex("RegisteredAt")
                        .HasDatabaseName("ix_books_registered_at");

                    b.HasIndex("LibraryId", "LangCode", "SearchTitle")
                        .HasDatabaseName("ix_books_library_id_lang_code_search_title");

                    b.HasIndex("LibraryId", "RelPath", "EntryName")
                        .IsUnique()
                        .HasDatabaseName("ix_books_library_id_rel_path_entry_name");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("LibraryId", "RelPath", "EntryName"), false);

                    b.HasIndex(new[] { "SearchTitle" }, "ix_books_search_title_trgm")
                        .HasDatabaseName("ix_books_search_title_trgm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex(new[] { "SearchTitle" }, "ix_books_search_title_trgm"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex(new[] { "SearchTitle" }, "ix_books_search_title_trgm"), new[] { "gin_trgm_ops" });

                    b.ToTable("books", (string)null);
                });

            modelBuilder.Entity("Nopds.Domain.Entities.BookAuthor", b =>
                {
                    b.Property<long>("BookId")
                        .HasColumnType("bigint")
                        .HasColumnName("book_id");

                    b.Property<long>("AuthorId")
                        .HasColumnType("bigint")
                        .HasColumnName("author_id");

                    b.Property<short>("Position")
                        .HasColumnType("smallint")
                        .HasColumnName("position");

                    b.HasKey("BookId", "AuthorId")
                        .HasName("pk_book_authors");

                    b.HasIndex("AuthorId")
                        .HasDatabaseName("ix_book_authors_author_id");

                    b.ToTable("book_authors", (string)null);
                });

            modelBuilder.Entity("Nopds.Domain.Entities.BookGenre", b =>
                {
                    b.Property<long>("BookId")
                        .HasColumnType("bigint")
                        .HasColumnName("book_id");

                    b.Property<int>("GenreId")
                        .HasColumnType("integer")
                        .HasColumnName("genre_id");

                    b.HasKey("BookId", "GenreId")
                        .HasName("pk_book_genres");

                    b.HasIndex("GenreId")
                        .HasDatabaseName("ix_book_genres_genre_id");

                    b.ToTable("book_genres", (string)null);
                });

            modelBuilder.Entity("Nopds.Domain.Entities.BookSeries", b =>
                {
                    b.Property<long>("BookId")
                        .HasColumnType("bigint")
                        .HasColumnName("book_id");

                    b.Property<long>("SeriesId")
                        .HasColumnType("bigint")
                        .HasColumnName("series_id");

                    b.Property<int>("SerNo")
                        .HasColumnType("integer")
                        .HasColumnName("ser_no");

                    b.HasKey("BookId", "SeriesId")
                        .HasName("pk_book_series");

                    b.HasIndex("SeriesId")
                        .HasDatabaseName("ix_book_series_series_id");

                    b.ToTable("book_series", (string)null);
                });

            modelBuilder.Entity("Nopds.Domain.Entities.Catalog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("LibraryId")
                        .HasColumnType("integer")
                        .HasColumnName("library_id");

                    b.Property<DateTimeOffset?>("Mtime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("mtime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("name");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint")
                        .HasColumnName("parent_id");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("path");

                    b.Property<long>("Size")
                        .HasColumnType("bigint")
                        .HasColumnName("size");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_catalogs");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_catalogs_parent_id");

                    b.HasIndex("LibraryId", "Path")
                        .IsUnique()
                        .HasDatabaseName("ix_catalogs_library_id_path");

                    b.ToTable("catalogs", (string)null);
                });

            modelBuilder.Entity("Nopds.Domain.Entities.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("section");

                    b.HasKey("Id")
                        .HasName("pk_genres");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_genres_code");

                    b.HasIndex("Section")
                        .HasDatabaseName("ix_genres_section");

                    b.ToTable("genres", (string)null);
                });

            modelBuilder.Entity("Nopds.Domain.Entities.KoreaderProgress", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("Document")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("document");

                    b.Property<string>("Device")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("device");

                    b.Property<string>("DeviceId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("device_id");

                    b.Property<double>("Percentage")
                        .HasColumnType("double precision")
                        .HasColumnName("percentage");

                    b.Property<string>("Progress")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("progress");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId", "Document")
                        .HasName("pk_koreader_progress");

                    b.ToTable("koreader_progress", (string)null);
                });

            modelBuilder.Entity("Nopds.Domain.Entities.Library", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("DeleteLogical")
                        .HasColumnType("boolean")
                        .HasColumnName("delete_logical");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.PrimitiveCollection<string[]>("Extensions")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("extensions");

                    b.Property<bool>("HashContent")
                        .HasColumnType("boolean")
                        .HasColumnName("hash_content");

                    b.Property<bool>("InpxEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("inpx_enabled");

                    b.Property<bool>("InpxSkipUnchanged")
                        .HasColumnType("boolean")
                        .HasColumnName("inpx_skip_unchanged");

                    b.Property<bool>("InpxTestFiles")
                        .HasColumnType("boolean")
                        .HasColumnName("inpx_test_files");

                    b.Property<bool>("InpxTestZip")
                        .HasColumnType("boolean")
                        .HasColumnName("inpx_test_zip");

                    b.Property<bool>("IsUploads")
                        .HasColumnType("boolean")
                        .HasColumnName("is_uploads");

                    b.Property<DateTimeOffset?>("LastScanFinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_scan_finished_at");

                    b.Property<DateTimeOffset?>("LastScanStartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_scan_started_at");

                    b.Property<string>("LastScanSummary")
                        .HasColumnType("text")
                        .HasColumnName("last_scan_summary");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<string>("RootPath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("root_path");

                    b.Property<string>("ScanCron")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("scan_cron");

                    b.Property<bool>("ScanZip")
                        .HasColumnType("boolean")
                        .HasColumnName("scan_zip");

                    b.Property<bool>("WatchEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("watch_enabled");

                    b.Property<string>("ZipCodepage")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("zip_codepage");

                    b.HasKey("Id")
                        .HasName("pk_libraries");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_libraries_name");

                    b.ToTable("libraries", (string)null);
                });

            modelBuilder.Entity("Nopds.Domain.Entities.ReadingState", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<long>("BookId")
                        .HasColumnType("bigint")
                        .HasColumnName("book_id");

                    b.Property<DateTimeOffset>("AddedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at");

                    b.Property<bool>("Finished")
                        .HasColumnType("boolean")
                        .HasColumnName("finished");

                    b.Property<DateTimeOffset>("LastOpenedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_opened_at");

                    b.Property<string>("Location")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("location");

                    b.Property<double>("Progress")
                        .HasColumnType("double precision")
                        .HasColumnName("progress");

                    b.HasKey("UserId", "BookId")
                        .HasName("pk_reading_states");

                    b.HasIndex("BookId")
                        .HasDatabaseName("ix_reading_states_book_id");

                    b.HasIndex("UserId", "LastOpenedAt")
                        .HasDatabaseName("ix_reading_states_user_id_last_opened_at");

                    b.ToTable("reading_states", (string)null);
                });

            modelBuilder.Entity("Nopds.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("ReplacedByHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("replaced_by_hash");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("user_agent");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("Nopds.Domain.Entities.Series", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("LangCode")
                        .HasColumnType("integer")
                        .HasColumnName("lang_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("SearchName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("search_name");

                    b.HasKey("Id")
                        .HasName("pk_series");

                    b.HasIndex("LangCode", "SearchName")
                        .HasDatabaseName("ix_series_lang_code_search_name");

                    b.HasIndex(new[] { "SearchName" }, "ix_series_search_name")
                        .IsUnique()
                        .HasDatabaseName("ix_series_search_name");

                    b.HasIndex(new[] { "SearchName" }, "ix_series_search_name_trgm")
                        .HasDatabaseName("ix_series_search_name_trgm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex(new[] { "SearchName" }, "ix_series_search_name_trgm"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex(new[] { "SearchName" }, "ix_series_search_name_trgm"), new[] { "gin_trgm_ops" });

                    b.ToTable("series", (string)null);
                });

            modelBuilder.Entity("Nopds.Domain.Entities.Setting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("key");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("value");

                    b.HasKey("Key")
                        .HasName("pk_settings");

                    b.ToTable("settings", (string)null);
                });

            modelBuilder.Entity("Nopds.Domain.Entities.Upload", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("boolean")
                        .HasColumnName("is_private");

                    b.Property<int>("LibraryId")
                        .HasColumnType("integer")
                        .HasColumnName("library_id");

                    b.Property<string>("OriginalName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("original_name");

                    b.Property<string>("RelPath")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("rel_path");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_uploads");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_uploads_user_id");

                    b.HasIndex("LibraryId", "RelPath")
                        .IsUnique()
                        .HasDatabaseName("ix_uploads_library_id_rel_path");

                    b.ToTable("uploads", (string)null);
                });

            modelBuilder.Entity("Nopds.Infrastructure.Identity.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.PrimitiveCollection<int[]>("AllowedLibraryIds")
                        .HasColumnType("integer[]")
                        .HasColumnName("allowed_library_ids");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<string>("FeedToken")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("feed_token");

                    b.Property<bool>("HideDuplicates")
                        .HasColumnType("boolean")
                        .HasColumnName("hide_duplicates");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean")
                        .HasColumnName("is_admin");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("boolean")
                        .HasColumnName("is_approved");

                    b.Property<string>("KosyncKeyHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("kosync_key_hash");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("PreferredFormat")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("preferred_format");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<string>("TelegramUsername")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("telegram_username");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UiLanguage")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("ui_language");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("FeedToken")
                        .IsUnique()
                        .HasDatabaseName("ix_users_feed_token");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("TelegramUsername")
                        .HasDatabaseName("ix_users_telegram_username");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Nopds.Infrastructure.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_claims_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Nopds.Infrastructure.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_logins_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Nopds.Infrastructure.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_tokens_users_user_id");
                });

            modelBuilder.Entity("Nopds.Domain.Entities.Book", b =>
                {
                    b.HasOne("Nopds.Domain.Entities.Catalog", "Catalog")
                        .WithMany()
                        .HasForeignKey("CatalogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_books_catalogs_catalog_id");

                    b.HasOne("Nopds.Domain.Entities.Library", "Library")
                        .WithMany()
                        .HasForeignKey("LibraryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_books_libraries_library_id");

                    b.Navigation("Catalog");

                    b.Navigation("Library");
                });

            modelBuilder.Entity("Nopds.Domain.Entities.BookAuthor", b =>
                {
                    b.HasOne("Nopds.Domain.Entities.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_book_authors_authors_author_id");

                    b.HasOne("Nopds.Domain.Entities.Book", "Book")
                        .WithMany("Authors")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_book_authors_books_book_id");

                    b.Navigation("Author");

                    b.Navigation("Book");
                });

            modelBuilder.Entity("Nopds.Domain.Entities.BookGenre", b =>
                {
                    b.HasOne("Nopds.Domain.Entities.Book", "Book")
                        .WithMany("Genres")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_book_genres_books_book_id");

                    b.HasOne("Nopds.Domain.Entities.Genre", "Genre")
                        .WithMany("Books")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_book_genres_genres_genre_id");

                    b.Navigation("Book");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("Nopds.Domain.Entities.BookSeries", b =>
                {
                    b.HasOne("Nopds.Domain.Entities.Book", "Book")
                        .WithMany("Series")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_book_series_books_book_id");

                    b.HasOne("Nopds.Domain.Entities.Series", "Series")
                        .WithMany("Books")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_book_series_series_series_id");

                    b.Navigation("Book");

                    b.Navigation("Series");
                });

            modelBuilder.Entity("Nopds.Domain.Entities.Catalog", b =>
                {
                    b.HasOne("Nopds.Domain.Entities.Library", "Library")
                        .WithMany()
                        .HasForeignKey("LibraryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_catalogs_libraries_library_id");

                    b.HasOne("Nopds.Domain.Entities.Catalog", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_catalogs_catalogs_parent_id");

                    b.Navigation("Library");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Nopds.Domain.Entities.KoreaderProgress", b =>
                {
                    b.HasOne("Nopds.Infrastructure.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_koreader_progress_users_user_id");
                });

            modelBuilder.Entity("Nopds.Domain.Entities.ReadingState", b =>
                {
                    b.HasOne("Nopds.Domain.Entities.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reading_states_books_book_id");

                    b.HasOne("Nopds.Infrastructure.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reading_states_users_user_id");

                    b.Navigation("Book");
                });

            modelBuilder.Entity("Nopds.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("Nopds.Infrastructure.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_user_id");
                });

            modelBuilder.Entity("Nopds.Domain.Entities.Upload", b =>
                {
                    b.HasOne("Nopds.Domain.Entities.Library", "Library")
                        .WithMany()
                        .HasForeignKey("LibraryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_uploads_libraries_library_id");

                    b.HasOne("Nopds.Infrastructure.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_uploads_users_user_id");

                    b.Navigation("Library");
                });

            modelBuilder.Entity("Nopds.Domain.Entities.Author", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("Nopds.Domain.Entities.Book", b =>
                {
                    b.Navigation("Authors");

                    b.Navigation("Genres");

                    b.Navigation("Series");
                });

            modelBuilder.Entity("Nopds.Domain.Entities.Genre", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("Nopds.Domain.Entities.Series", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
