<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Telegram.Bot" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Nopds.Infrastructure\Nopds.Infrastructure.csproj" />
    <ProjectReference Include="..\Nopds.Conversion\Nopds.Conversion.csproj" />
  </ItemGroup>

</Project>
