<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SkiaSharp" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux.NoDependencies" />
    <PackageReference Include="System.IO.Hashing" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Nopds.Domain\Nopds.Domain.csproj" />
  </ItemGroup>

</Project>
